version: '3'
services:
  todotests:
    depends_on:
      - frontend
      - backend
    environment:
      - FRONT_HOST=frontend
  todofront:
    image: todofrontend
    ports:
      -3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_HOST=backend
  todoback:
    image: todofrontend
    ports:
      - 3001:3001
    depends_on:
      - backend
    environment:
      - REACT_APP_API_HOST=backend
  # ...