version: '3'

services:
  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    networks:
      - rede-virtual

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - rede-virtual

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - rede-virtual
      
networks:
  rede-virtual: